version: '3.8'
services:
 sql-server-db:
  container_name: sql-server-db
  image: mcr.microsoft.com/mssql/server:2019-latest
  ports:
   - '1433:1433'
  environment:
   SA_PASSWORD: "2545V0lk9198"
   ACCEPT_EULA: "Y"
  volumes:
   - ./SQL:/var/lib/mssql/sqlScripts/:z
